
name: Github Pages Deploy 

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: GitHub Actions - Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install and build
        run: npm install && cp dist/test-angular-deploy/index.html dist/test-angular-deploy/404.html
      
      - name: Deploy
        uses: JamesIves/github-page-deploy-action@4.1.1
        with:
          branch: master
          folder: test-angular-deploy/dist/test-angular-deploy
